In [7]:
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn import preprocessing
import numpy as np

In [8]:
dataset = np.array([
                    ['Low' ,'High','Sunny'  ,'Grassy'  ,'Open air','Low' ,'No'],
                    ['Mild','Low' ,'Rainy'  ,'Clay'    ,'Enclosed','Mild','Yes'],
                    ['High','Mild','Outcast','Cemented','Open air','High','Yes'],
                    ['Low' ,'Mild','Rainy'  ,'Clay'    ,'Enclosed','Mild','No'],
                    ['Mild','Low' ,'Outcast','Clay'    ,'Open air','High','Yes'],
                    ['High','High','Outcast','Cemented','Enclosed','Low' ,'Yes'],
                    ['Low' ,'Low' ,'Sunny'  ,'Grassy'  ,'Open air','Mild','Yes'],
                    ['Mild','Mild','Sunny'  ,'Grassy'  ,'Enclosed','High','Yes'],
                    ['High','High','Rainy'  ,'Clay'    ,'Open air','Low' ,'Yes'],
                    ['Low' ,'High','Outcast','Cemented','Enclosed','Mild','Yes'],
                    ['Mild','Low' ,'Sunny'  ,'Clay'    ,'Open air','High','Yes'],
                    ['High','Mild','Sunny'  ,'Grassy'  ,'Enclosed','High','Yes'],
                    ['Low' ,'Mild','Rainy'  ,'Clay'    ,'Open air','High','Yes'],
                    ['Mild','Low' ,'Outcast','Cemented','Enclosed','Low' ,'Yes'],
                    ['High','Low' ,'Sunny'  ,'Cemented','Open air','Low' ,'Yes'],
                    ['Low' ,'Mild','Outcast','Grassy'  ,'Enclosed','Low' ,'Yes'],
                    ['Mild','Mild','Sunny'  ,'Clay'    ,'Open air','Mild','Yes'],
                    ['High','High','Rainy'  ,'Grassy'  ,'Enclosed','High','Yes'],
                    ['Low' ,'High','Outcast','Clay'    ,'Open air','Low' ,'Yes'],
                    ['Mild','High','Outcast','Cemented','Enclosed','Mild','Yes']])

In [9]:
print(dataset)

[['Low' 'High' 'Sunny' 'Grassy' 'Open air' 'Low' 'No']
 ['Mild' 'Low' 'Rainy' 'Clay' 'Enclosed' 'Mild' 'Yes']
 ['High' 'Mild' 'Outcast' 'Cemented' 'Open air' 'High' 'Yes']
 ['Low' 'Mild' 'Rainy' 'Clay' 'Enclosed' 'Mild' 'No']
 ['Mild' 'Low' 'Outcast' 'Clay' 'Open air' 'High' 'Yes']
 ['High' 'High' 'Outcast' 'Cemented' 'Enclosed' 'Low' 'Yes']
 ['Low' 'Low' 'Sunny' 'Grassy' 'Open air' 'Mild' 'Yes']
 ['Mild' 'Mild' 'Sunny' 'Grassy' 'Enclosed' 'High' 'Yes']
 ['High' 'High' 'Rainy' 'Clay' 'Open air' 'Low' 'Yes']
 ['Low' 'High' 'Outcast' 'Cemented' 'Enclosed' 'Mild' 'Yes']
 ['Mild' 'Low' 'Sunny' 'Clay' 'Open air' 'High' 'Yes']
 ['High' 'Mild' 'Sunny' 'Grassy' 'Enclosed' 'High' 'Yes']
 ['Low' 'Mild' 'Rainy' 'Clay' 'Open air' 'High' 'Yes']
 ['Mild' 'Low' 'Outcast' 'Cemented' 'Enclosed' 'Low' 'Yes']
 ['High' 'Low' 'Sunny' 'Cemented' 'Open air' 'Low' 'Yes']
 ['Low' 'Mild' 'Outcast' 'Grassy' 'Enclosed' 'Low' 'Yes']
 ['Mild' 'Mild' 'Sunny' 'Clay' 'Open air' 'Mild' 'Yes']
 ['High' 'High' 'Rainy' 'G

In [10]:
Features = dataset[:,0:-1]

In [11]:
print(Features)

[['Low' 'High' 'Sunny' 'Grassy' 'Open air' 'Low']
 ['Mild' 'Low' 'Rainy' 'Clay' 'Enclosed' 'Mild']
 ['High' 'Mild' 'Outcast' 'Cemented' 'Open air' 'High']
 ['Low' 'Mild' 'Rainy' 'Clay' 'Enclosed' 'Mild']
 ['Mild' 'Low' 'Outcast' 'Clay' 'Open air' 'High']
 ['High' 'High' 'Outcast' 'Cemented' 'Enclosed' 'Low']
 ['Low' 'Low' 'Sunny' 'Grassy' 'Open air' 'Mild']
 ['Mild' 'Mild' 'Sunny' 'Grassy' 'Enclosed' 'High']
 ['High' 'High' 'Rainy' 'Clay' 'Open air' 'Low']
 ['Low' 'High' 'Outcast' 'Cemented' 'Enclosed' 'Mild']
 ['Mild' 'Low' 'Sunny' 'Clay' 'Open air' 'High']
 ['High' 'Mild' 'Sunny' 'Grassy' 'Enclosed' 'High']
 ['Low' 'Mild' 'Rainy' 'Clay' 'Open air' 'High']
 ['Mild' 'Low' 'Outcast' 'Cemented' 'Enclosed' 'Low']
 ['High' 'Low' 'Sunny' 'Cemented' 'Open air' 'Low']
 ['Low' 'Mild' 'Outcast' 'Grassy' 'Enclosed' 'Low']
 ['Mild' 'Mild' 'Sunny' 'Clay' 'Open air' 'Mild']
 ['High' 'High' 'Rainy' 'Grassy' 'Enclosed' 'High']
 ['Low' 'High' 'Outcast' 'Clay' 'Open air' 'Low']
 ['Mild' 'High' 'Outcast

In [12]:
target = dataset[:,-1]

In [13]:
print(target)

['No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes']


In [14]:
enc = preprocessing.OrdinalEncoder()

OrdinalEncoder()


In [15]:
enc.fit(Features)
print(Features)

[['Low' 'High' 'Sunny' 'Grassy' 'Open air' 'Low']
 ['Mild' 'Low' 'Rainy' 'Clay' 'Enclosed' 'Mild']
 ['High' 'Mild' 'Outcast' 'Cemented' 'Open air' 'High']
 ['Low' 'Mild' 'Rainy' 'Clay' 'Enclosed' 'Mild']
 ['Mild' 'Low' 'Outcast' 'Clay' 'Open air' 'High']
 ['High' 'High' 'Outcast' 'Cemented' 'Enclosed' 'Low']
 ['Low' 'Low' 'Sunny' 'Grassy' 'Open air' 'Mild']
 ['Mild' 'Mild' 'Sunny' 'Grassy' 'Enclosed' 'High']
 ['High' 'High' 'Rainy' 'Clay' 'Open air' 'Low']
 ['Low' 'High' 'Outcast' 'Cemented' 'Enclosed' 'Mild']
 ['Mild' 'Low' 'Sunny' 'Clay' 'Open air' 'High']
 ['High' 'Mild' 'Sunny' 'Grassy' 'Enclosed' 'High']
 ['Low' 'Mild' 'Rainy' 'Clay' 'Open air' 'High']
 ['Mild' 'Low' 'Outcast' 'Cemented' 'Enclosed' 'Low']
 ['High' 'Low' 'Sunny' 'Cemented' 'Open air' 'Low']
 ['Low' 'Mild' 'Outcast' 'Grassy' 'Enclosed' 'Low']
 ['Mild' 'Mild' 'Sunny' 'Clay' 'Open air' 'Mild']
 ['High' 'High' 'Rainy' 'Grassy' 'Enclosed' 'High']
 ['Low' 'High' 'Outcast' 'Clay' 'Open air' 'Low']
 ['Mild' 'High' 'Outcast

In [16]:
features = enc.transform(Features)

In [17]:
print(features)

[[1. 0. 2. 2. 1. 1.]
 [2. 1. 1. 1. 0. 2.]
 [0. 2. 0. 0. 1. 0.]
 [1. 2. 1. 1. 0. 2.]
 [2. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 1. 2. 2. 1. 2.]
 [2. 2. 2. 2. 0. 0.]
 [0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 2.]
 [2. 1. 2. 1. 1. 0.]
 [0. 2. 2. 2. 0. 0.]
 [1. 2. 1. 1. 1. 0.]
 [2. 1. 0. 0. 0. 1.]
 [0. 1. 2. 0. 1. 1.]
 [1. 2. 0. 2. 0. 1.]
 [2. 2. 2. 1. 1. 2.]
 [0. 0. 1. 2. 0. 0.]
 [1. 0. 0. 1. 1. 1.]
 [2. 0. 0. 0. 0. 2.]]


In [18]:
model = Perceptron()
fitted = model.fit(features, target)

In [19]:
guess = np.array([["High","High","Rainy","Clay","Open air","Low"]])


In [20]:
prediction = fitted.predict(enc.transform(guess))

In [21]:
print(prediction)

['No']


In [22]:
guess = np.array([["High","Low","Sunny","Cemented","Open air","High"]])


In [23]:
prediction = fitted.predict(enc.transform(guess))

In [24]:
print(prediction)

['Yes']
